# Converts images in templates/ to templates-manifest.js + templates-base64.js
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$templatesPath = Join-Path $scriptPath "templates"
$manifestFile = Join-Path $scriptPath "templates-manifest.js"
$base64File = Join-Path $scriptPath "templates-base64.js"

if (-not (Test-Path $templatesPath)) {
    New-Item -ItemType Directory -Path $templatesPath | Out-Null
    Write-Host "Created templates folder. Add PNG/JPG files and run again."
    exit 0
}

function Get-NaturalSortKey($name) {
    if ($name -match '^template(\d+)$') { return [int]$Matches[1] }
    return 99999
}

$files = Get-ChildItem -Path $templatesPath -File | Where-Object {
    $_.Extension -match '^\.(png|jpe?g)$'
} | Sort-Object { Get-NaturalSortKey ($_.BaseName) }, Name

if ($files.Count -eq 0) {
    Write-Host "No images in templates/ — keeping existing JS files."
    exit 0
}

$manifest = @()
$base64List = @()

foreach ($file in $files) {
    $name = $file.BaseName
    $relPath = "templates/$($file.Name)"
    $manifest += @{ name = $name; path = $relPath }

    $bytes = [System.IO.File]::ReadAllBytes($file.FullName)
    $b64 = [System.Convert]::ToBase64String($bytes)
    $mime = switch ($file.Extension.ToLower()) {
        '.png' { 'image/png' }
        '.jpg' { 'image/jpeg' }
        '.jpeg' { 'image/jpeg' }
        default { 'image/png' }
    }
    $base64List += @{ name = $name; data = "data:$mime;base64,$b64" }
}

$manifestJson = ($manifest | ConvertTo-Json -Depth 5) -replace '\r?\n', ''
$manifestJs = @"
// Generated by convert-templates.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
const templatesManifest = $manifestJson;
"@

$base64Json = ($base64List | ConvertTo-Json -Depth 5)
$base64Js = @"
// Generated by convert-templates.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
const templatesBase64 = $base64Json;
"@

[System.IO.File]::WriteAllText($manifestFile, $manifestJs, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText($base64File, $base64Js, [System.Text.UTF8Encoding]::new($false))

Write-Host "Done: $($files.Count) template(s)"
Write-Host "  -> templates-manifest.js"
Write-Host "  -> templates-base64.js"
