# Converts images in templates/ to templates-manifest.js + templates-base64.js
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$templatesPath = Join-Path $scriptPath "templates"
$manifestFile = Join-Path $scriptPath "templates-manifest.js"
$base64File = Join-Path $scriptPath "templates-base64.js"
$thumbsFile = Join-Path $scriptPath "templates-thumbs.js"
$chunksDir = Join-Path $scriptPath "templates-data"

if (-not (Test-Path $templatesPath)) {
    New-Item -ItemType Directory -Path $templatesPath | Out-Null
    Write-Host "Created templates folder. Add PNG/JPG files and run again."
    exit 0
}

function Get-NaturalSortKey($name) {
    if ($name -match '^template(\d+)$') { return [int]$Matches[1] }
    return 99999
}

$files = Get-ChildItem -Path $templatesPath -File | Where-Object {
    $_.Extension -match '^\.(png|jpe?g)$'
} | Sort-Object { Get-NaturalSortKey ($_.BaseName) }, Name

if ($files.Count -eq 0) {
    Write-Host "No images in templates/ — keeping existing JS files."
    exit 0
}

$manifest = @()
$base64List = @()
$thumbList = @()

Add-Type -AssemblyName System.Drawing
New-Item -ItemType Directory -Force -Path $chunksDir | Out-Null

foreach ($file in $files) {
    $name = $file.BaseName
    $relPath = "templates/$($file.Name)"
    $manifest += @{ name = $name; path = $relPath }

    $bytes = [System.IO.File]::ReadAllBytes($file.FullName)
    $b64 = [System.Convert]::ToBase64String($bytes)
    $mime = switch ($file.Extension.ToLower()) {
        '.png' { 'image/png' }
        '.jpg' { 'image/jpeg' }
        '.jpeg' { 'image/jpeg' }
        default { 'image/png' }
    }
    $dataUrl = "data:$mime;base64,$b64"
    $base64List += @{ name = $name; data = $dataUrl }

    # Per-template chunk for lazy loading on slow/blocked networks
    $chunkJs = "// $name`r`nwindow.__tplChunk=$([char]34)$dataUrl$([char]34);"
    [System.IO.File]::WriteAllText((Join-Path $chunksDir "$name.js"), $chunkJs, [System.Text.UTF8Encoding]::new($false))

    # Gallery thumbnail (~160px wide JPEG)
    $img = [System.Drawing.Image]::FromFile($file.FullName)
    $tw = 160
    $th = [Math]::Max(1, [int]($img.Height * (160.0 / $img.Width)))
    $bmp = New-Object System.Drawing.Bitmap $tw, $th
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.DrawImage($img, 0, 0, $tw, $th)
    $ms = New-Object IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Jpeg)
    $tb64 = [Convert]::ToBase64String($ms.ToArray())
    $thumbList += @{ name = $name; thumb = "data:image/jpeg;base64,$tb64" }
    $g.Dispose(); $bmp.Dispose(); $img.Dispose()
}

$manifestJson = ($manifest | ConvertTo-Json -Depth 5) -replace '\r?\n', ''
$manifestJs = @"
// Generated by convert-templates.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
const templatesManifest = $manifestJson;
"@

$base64Json = ($base64List | ConvertTo-Json -Depth 5)
$base64Js = @"
// Generated by convert-templates.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
const templatesBase64 = $base64Json;
"@

[System.IO.File]::WriteAllText($manifestFile, $manifestJs, [System.Text.UTF8Encoding]::new($false))
[System.IO.File]::WriteAllText($base64File, $base64Js, [System.Text.UTF8Encoding]::new($false))

$thumbJson = ($thumbList | ConvertTo-Json -Compress -Depth 3)
$thumbJs = @"
// Generated by convert-templates.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
const templatesThumbs = $thumbJson;
"@
[System.IO.File]::WriteAllText($thumbsFile, $thumbJs, [System.Text.UTF8Encoding]::new($false))

Write-Host "Done: $($files.Count) template(s)"
Write-Host "  -> templates-manifest.js"
Write-Host "  -> templates-base64.js"
Write-Host "  -> templates-thumbs.js"
Write-Host "  -> templates-data/ ($($files.Count) chunks)"
