# Generates templates-thumbs.js — small embedded gallery thumbnails
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$templatesPath = Join-Path $scriptPath "templates"
$outFile = Join-Path $scriptPath "templates-thumbs.js"

Add-Type -AssemblyName System.Drawing

function Get-NaturalSortKey($name) {
    if ($name -match '^template(\d+)$') { return [int]$Matches[1] }
    return 99999
}

$files = Get-ChildItem -Path $templatesPath -File | Where-Object {
    $_.Extension -match '^\.(png|jpe?g)$'
} | Sort-Object { Get-NaturalSortKey ($_.BaseName) }, Name

$list = @()
foreach ($file in $files) {
    $img = [System.Drawing.Image]::FromFile($file.FullName)
    $tw = 160
    $th = [Math]::Max(1, [int]($img.Height * (160.0 / $img.Width)))
    $bmp = New-Object System.Drawing.Bitmap $tw, $th
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.DrawImage($img, 0, 0, $tw, $th)
    $ms = New-Object IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Jpeg)
    $b64 = [Convert]::ToBase64String($ms.ToArray())
    $list += @{ name = $file.BaseName; thumb = "data:image/jpeg;base64,$b64" }
    $g.Dispose(); $bmp.Dispose(); $img.Dispose()
}

$json = ($list | ConvertTo-Json -Compress -Depth 3)
$js = "// Generated by generate-thumbs.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')`nconst templatesThumbs = $json;"
[System.IO.File]::WriteAllText($outFile, $js, [System.Text.UTF8Encoding]::new($false))
Write-Host "Done: $($list.Count) thumbs -> templates-thumbs.js ($((Get-Item $outFile).Length) bytes)"
